name: multi_module_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  core:
    path: modules/core
  core_ui:
    path: modules/core_ui
  user:
    path: modules/user
  product:
    path: modules/product
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/products.json
    - assets/json/user.json