name: user
description: User module containing user-related features
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  core_ui:
    path: ../core_ui
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
