name: core
description: Core module containing data, domain, and repositories
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_serializable: ^6.9.3

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

